In [1]:
import tensorflow as tf

In [2]:
vocab = {
    'i':0,
    'need':1,
    'some':2,
    'more':3,
    'coffee':4,
    'cake':5,
    'cat':6,
    'dog':7
}

In [3]:
sentence = 'i i i i need some more coffee coffee coffee'

In [4]:
_input = [vocab[w] for w in sentence.split()]

In [5]:
vocab_size = len(vocab)

In [6]:
one_hot = tf.one_hot(_input,vocab_size)

In [7]:
print(one_hot)

tf.Tensor(
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]], shape=(10, 8), dtype=float32)


In [8]:
distribution_size = 2

In [10]:
linear = tf.keras.layers.Dense(units=distribution_size,use_bias=False)
one_hot_linear = linear(one_hot)

In [11]:
print(linear.weights[0].numpy())

[[ 0.34774637 -0.59614193]
 [-0.2621181  -0.35469672]
 [ 0.04668111  0.12566209]
 [-0.51403195 -0.08872718]
 [-0.5864217  -0.24660307]
 [-0.36457646  0.7495549 ]
 [ 0.24609423  0.3336593 ]
 [ 0.34923232  0.50892544]]


In [12]:
print(one_hot_linear.numpy())

[[ 0.34774637 -0.59614193]
 [ 0.34774637 -0.59614193]
 [ 0.34774637 -0.59614193]
 [ 0.34774637 -0.59614193]
 [-0.2621181  -0.35469672]
 [ 0.04668111  0.12566209]
 [-0.51403195 -0.08872718]
 [-0.5864217  -0.24660307]
 [-0.5864217  -0.24660307]
 [-0.5864217  -0.24660307]]


In [13]:
words = tf.constant([[3,57,35]])

In [18]:
print('embedding 진행할 문장')
print(words.shape)

embedding 진행할 문장
(1, 3)


In [15]:
embedding_layer = tf.keras.layers.Embedding(input_dim=64,output_dim=100)

In [19]:
print('embedding된 문장')
print(embedding_layer(words).shape)

embedding된 문장
(1, 3, 100)


In [20]:
print('embedding layer weight')
print(embedding_layer.weights[0].shape)

embedding layer weight
(64, 100)


In [29]:
import numpy as np

In [30]:
raw_i = [
    '나는 학생입니다',
    '나는 좋은 선생님 입니다',
    '당신은 매우 좋은 선생님 입니다'
]

In [31]:
raw_l = [1,0,0]

In [32]:
words = []
for w in raw_i:
  words.extend(w.split())

In [33]:
print(words)

['나는', '학생입니다', '나는', '좋은', '선생님', '입니다', '당신은', '매우', '좋은', '선생님', '입니다']


In [34]:
words = list(dict.fromkeys(words))

In [35]:
print(words)

['나는', '학생입니다', '좋은', '선생님', '입니다', '당신은', '매우']


In [36]:
word_to_id = {'<PAD>':0,'<UNK>':1}

In [37]:
for w in words:
  word_to_id[w] = len(word_to_id)
  print(word_to_id)

{'<PAD>': 0, '<UNK>': 1, '나는': 2}
{'<PAD>': 0, '<UNK>': 1, '나는': 2, '학생입니다': 3}
{'<PAD>': 0, '<UNK>': 1, '나는': 2, '학생입니다': 3, '좋은': 4}
{'<PAD>': 0, '<UNK>': 1, '나는': 2, '학생입니다': 3, '좋은': 4, '선생님': 5}
{'<PAD>': 0, '<UNK>': 1, '나는': 2, '학생입니다': 3, '좋은': 4, '선생님': 5, '입니다': 6}
{'<PAD>': 0, '<UNK>': 1, '나는': 2, '학생입니다': 3, '좋은': 4, '선생님': 5, '입니다': 6, '당신은': 7}
{'<PAD>': 0, '<UNK>': 1, '나는': 2, '학생입니다': 3, '좋은': 4, '선생님': 5, '입니다': 6, '당신은': 7, '매우': 8}


In [38]:
word_to_id.items()

dict_items([('<PAD>', 0), ('<UNK>', 1), ('나는', 2), ('학생입니다', 3), ('좋은', 4), ('선생님', 5), ('입니다', 6), ('당신은', 7), ('매우', 8)])

In [39]:
id_to_words = {i:w for w,i in word_to_id.items()}

In [40]:
print(id_to_words)

{0: '<PAD>', 1: '<UNK>', 2: '나는', 3: '학생입니다', 4: '좋은', 5: '선생님', 6: '입니다', 7: '당신은', 8: '매우'}


In [41]:
train_inputs = []

In [43]:
for s in raw_i:
  row = [word_to_id[w] for w in s.split()]
  row+=[0]*(5-len(row))
  train_inputs.append(row)
train_inputs = np.array(train_inputs)

In [44]:
print(train_inputs)

[[2 3 0 0 0]
 [2 4 5 6 0]
 [7 8 4 5 6]]


In [48]:
train_inputs.shape

(3, 5)

In [49]:
onehot_matrix = np.eye(len(word_to_id))
print(onehot_matrix)

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [50]:
train_onehot = onehot_matrix[train_inputs]
print(train_onehot)

[[[0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0. 0.]]]


In [51]:
train_onehot.shape

(3, 5, 9)

In [53]:
x = np.argmax(train_onehot,axis=-1)

In [54]:
print(x)

[[2 3 0 0 0]
 [2 4 5 6 0]
 [7 8 4 5 6]]


In [55]:
import tensorflow as tf
import tensorflow.keras.layers as L

In [56]:
x_len = train_onehot.shape

In [57]:
print(x_len)

(3, 5, 9)


In [58]:
inp = tf.convert_to_tensor(x,dtype=tf.int32)
inp_len = tf.convert_to_tensor(x_len,dtype=tf.int32)

In [59]:
print(inp)
print(inp_len)

tf.Tensor(
[[2 3 0 0 0]
 [2 4 5 6 0]
 [7 8 4 5 6]], shape=(3, 5), dtype=int32)
tf.Tensor([3 5 9], shape=(3,), dtype=int32)


In [60]:
inp, inp_len

(<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
 array([[2, 3, 0, 0, 0],
        [2, 4, 5, 6, 0],
        [7, 8, 4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 5, 9], dtype=int32)>)

In [61]:
vocab_size = 1000

In [62]:
dim = 10

In [63]:
embed = L.Embedding(vocab_size,dim)

In [64]:
a = embed(inp)

In [65]:
print(a)

tf.Tensor(
[[[-0.04844109  0.0195769   0.00714185  0.01799675  0.0399173
   -0.03393418 -0.04875145 -0.03822068 -0.03300587  0.04844636]
  [-0.02129778 -0.02841719  0.02642592 -0.02304951 -0.03642095
   -0.01159356 -0.00565584 -0.04896845  0.04762962  0.0023853 ]
  [ 0.03064987 -0.04958854  0.0197238  -0.04902286  0.03122986
    0.01931418  0.04733051 -0.01452804 -0.02486587 -0.046468  ]
  [ 0.03064987 -0.04958854  0.0197238  -0.04902286  0.03122986
    0.01931418  0.04733051 -0.01452804 -0.02486587 -0.046468  ]
  [ 0.03064987 -0.04958854  0.0197238  -0.04902286  0.03122986
    0.01931418  0.04733051 -0.01452804 -0.02486587 -0.046468  ]]

 [[-0.04844109  0.0195769   0.00714185  0.01799675  0.0399173
   -0.03393418 -0.04875145 -0.03822068 -0.03300587  0.04844636]
  [-0.03203613 -0.0266736  -0.01252514  0.00098108  0.04168684
    0.00477219 -0.02003236 -0.01964722  0.01951362 -0.02419589]
  [-0.00506864  0.04284108  0.03215705 -0.04536519 -0.01118358
   -0.01056136  0.03136357  0.0065652

In [66]:
a.shape

TensorShape([3, 5, 10])