토큰화

In [2]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence,Tokenizer

In [3]:
text = '해보지 않으면, 해낼 수 없다?'
result = text_to_word_sequence(text)
result1 = text.split()
print(text,result,result1,sep='\n')

해보지 않으면, 해낼 수 없다?
['해보지', '않으면', '해낼', '수', '없다']
['해보지', '않으면,', '해낼', '수', '없다?']


In [46]:
docs=['먼저 텍스트의 각 단어를 나누어 토큰화합니다.',
      '텍스트의 단어로 토큰화해야 딥러닝에서 인식됩니다.',
      '토큰화한 결과는 딥러닝에서 사용할 수 있습니다?']

In [47]:
token = Tokenizer()
token.fit_on_texts(docs)

display("단어 카운트",token.word_counts)

'단어 카운트'

OrderedDict([('먼저', 1),
             ('텍스트의', 2),
             ('각', 1),
             ('단어를', 1),
             ('나누어', 1),
             ('토큰화합니다', 1),
             ('단어로', 1),
             ('토큰화해야', 1),
             ('딥러닝에서', 2),
             ('인식됩니다', 1),
             ('토큰화한', 1),
             ('결과는', 1),
             ('사용할', 1),
             ('수', 1),
             ('있습니다', 1)])

In [48]:
print('문장 카운트',token.document_count)

문장 카운트 3


In [49]:
display('각 단어가 몇개의 문장에 포함되어 있는가',token.word_docs)

'각 단어가 몇개의 문장에 포함되어 있는가'

defaultdict(int,
            {'각': 1,
             '결과는': 1,
             '나누어': 1,
             '단어로': 1,
             '단어를': 1,
             '딥러닝에서': 2,
             '먼저': 1,
             '사용할': 1,
             '수': 1,
             '인식됩니다': 1,
             '있습니다': 1,
             '텍스트의': 2,
             '토큰화한': 1,
             '토큰화합니다': 1,
             '토큰화해야': 1})

In [50]:
display('각 단어에 매겨진 인덱스 값',token.word_index)

'각 단어에 매겨진 인덱스 값'

{'각': 4,
 '결과는': 12,
 '나누어': 6,
 '단어로': 8,
 '단어를': 5,
 '딥러닝에서': 2,
 '먼저': 3,
 '사용할': 13,
 '수': 14,
 '인식됩니다': 10,
 '있습니다': 15,
 '텍스트의': 1,
 '토큰화한': 11,
 '토큰화합니다': 7,
 '토큰화해야': 9}

원핫인코딩

In [44]:
text='오랫동안 꿈꾸는 이는 그 꿈을 닮아간다.'

token =Tokenizer()
token.fit_on_texts([text])
print(token.word_index)

{'오랫동안': 1, '꿈꾸는': 2, '이는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}


In [32]:
x = token.texts_to_sequences([text])
print(x)

[[1, 2, 3, 4, 5, 6]]


In [33]:
from tensorflow.keras.utils import to_categorical

In [34]:
word_size = len(token.word_index)+1
x = to_categorical(x,num_classes=word_size)
print(x)

[[[0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 1.]]]


In [40]:
from tensorflow.keras.layers import Embedding

model = Sequential()
model.add(Embedding(16,4))

In [56]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Flatten,Embedding
from tensorflow.keras.utils import to_categorical
from numpy import array

docs = ['너무 재밌네요','최고에요','참 잘 만든 영화예요','추천하고 싶은 영화입니다',
        '한번 더 보고싶네요','글쎄요','별로예요','생각보다 지루하네요','연기가 어색해요','재미없어요']

classes = array([1,1,1,1,1,0,0,0,0,0])

token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)

x = token.texts_to_sequences(docs)
print('리뷰 텍스트 토큰화\n',x)

padded_x = pad_sequences(x,4)
print('패딩\n',padded_x)

word_size = len(token.word_index)+1
# x = to_categorical(padded_x,num_classes=word_size)

model = Sequential()
model.add(Embedding(word_size,8,input_length=4))
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))
model.summary()

model.compile(optimizer='adam',loss='binary_crossentropy',
              metrics=['accuracy'])
model.fit(padded_x,classes,epochs=20)
print('accracy %.4f'%(model.evaluate(padded_x,classes)[1]))

{'너무': 1, '재밌네요': 2, '최고에요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고싶네요': 13, '글쎄요': 14, '별로예요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}
리뷰 텍스트 토큰화
 [[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13], [14], [15], [16, 17], [18, 19], [20]]
패딩
 [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]
Model: "sequential_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_10 (Embedding)    (None, 4, 8)              168       
                                                                 
 flatten_9 (Flatten)         (None, 32)                0         
                                                                 
 dense_9 (Dense)             (None, 1)                 33        
                                       