In [1]:
# 판다스의 자료구조 : 시리즈, 데이터프레임
import pandas as pd


In [8]:
# 시리즈 생성 Series(딕셔너리 또는 리스트, index = [])
sr = pd.Series({'a':1,'b':2,'c':3})
print(sr)

print(type(sr))

a    1
b    2
c    3
dtype: int64
<class 'pandas.core.series.Series'>


In [10]:
#시리즈의 인덱스, 값
print(sr.index)
print(sr.values)

Index(['a', 'b', 'c'], dtype='object')
[1 2 3]


In [15]:
#시리즈를 접근하는 방법 : sr[index], sr[숫자인덱스]
print(sr['a'],sr[0])
print()
print(sr['a':'c'],sr[0:2],sep='\n')   # 인덱스명으로 접근시 end도 포함('c'), 숫자는 end 미포함(2)

1 1

a    1
b    2
c    3
dtype: int64
a    1
b    2
dtype: int64


In [16]:
# 리스트 또는 튜플을 시리즈로 만들면서 인덱스명 부여
list_data = ['명인','20-06-30','남',True]
sr1 = pd.Series(list_data,index=['이름','생년월일','성별','학생여부'])
print(sr1)


이름            명인
생년월일    20-06-30
성별             남
학생여부        True
dtype: object


In [19]:
sr1[ ['이름','생년월일'] ]

이름            명인
생년월일    20-06-30
dtype: object

In [24]:
print(sr1.dtype)        #시리즈에 저장된 데이터 타입 숫자 ->int64 문자->o(object)
print(type(sr1['이름']))
print(sr.dtype)        
print(type(sr['a']))

object
<class 'str'>
int64
<class 'numpy.int64'>


In [27]:
# 데이터프레임 : 시리즈가 여러개 묶여서 됨
# 딕셔너리로 데이터프레임 생성 -> 키가 컬럼으로 됨
dict_data = {'a':[1,2,3],'b':[4,5,6],'c':[7,8,9]}
df = pd.DataFrame(dict_data)
df

a  b  c
0  1  4  7
1  2  5  8
2  3  6  9

In [31]:
print(type(df))
print(df.dtypes)     # 각 컬럼의 데이터 타입
print(df.index)      # 데이터프레임의 인덱스 출력
print(df.values)     # 각 인덱스의 값 : 2차원 리스트

<class 'pandas.core.frame.DataFrame'>
a    int64
b    int64
c    int64
dtype: object
RangeIndex(start=0, stop=3, step=1)
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [35]:
# 2차원 리스트로 인덱스명과 컬럼명을 부여하면서 데이터프레임 생성
data = [[15,'남','덕영중'],[17,'여','수리중']]
df = pd.DataFrame(data,index=['준서', '예은'],
                 columns=['나이','성별','학교'])
df

나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [7]:
print(df.dtypes)
print()
print(df.index)
print()
print(df.columns)
print()

# 인덱스명을 변경 : 객체.index = [인덱스명,...]     기존의 정보 수정
# 컬럼명을 변경 : 객체.columns = [컬럼명,...]       기존의 정보 수정
# 준서, 예은 -> 학생1, 학생2
df.index = ['학생1','학생2']
print(df)
print()
df.columns = ['연령','남여', '소속']
print(df)

NameError: name 'df' is not defined

In [8]:
df

NameError: name 'df' is not defined

In [9]:
# 인덱스명과 컬럼명을 일부만 수정하고자 할 경우 
# object.rename(index={old:new, ...}, inplace=False)      inplace=True 해야 기존의 정보 수정
# object.column(column={old:new, ...}, inplace=False)
df.rename(index={'학생1':'준서'},columns={'남여':'성별'},inplace=True)


NameError: name 'df' is not defined

In [10]:
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

In [11]:
# 서준, 우현, 인아 로 인덱스 설정 하면서 exam_data를 이용하여 df을 생성
df = pd.DataFrame(exam_data, index=['서준','우현','인하'])
df

NameError: name 'pd' is not defined

In [12]:
# 행의 자료를 삭제 : 객체.drop(행인덱스 또는 배열, axis=0)
# 열(컬럼)의 자료를 삭제 : 객체.drop(열인덱스 또는 배열, axis=1)
# 서준과 우현의 자료 삭제
print(df.drop(['서준','우현'], axis=0))
print()
print(df.drop(['수학'], axis=1))



NameError: name 'df' is not defined

In [13]:
exam_data = [[ 90, 80, 70],  [ 98, 89, 95],
              [ 85, 95, 100],  [ 100, 90, 90]]
# exam_data 를 데이터프레임으로 생성 
# 인덱스명은 서준, 준서, 인아, 연아
# 컬럼명 추가 국어, 영어, 수학
# 수학 컬럼명을 체육으로 수정해서 기존 자료에 반영
# 영어 컬럼 자료 삭제 : 기존자료 미반영
# 서준 자료 삭제 : 기존자료미반영

df1 = pd.DataFrame(exam_data,index=['서준','준서','인아','연아'],columns=['국어','영어','수학'])
print(df1)
print()
df1.rename(columns={'수학':'체육'},inplace=True)
print(df1)
print()
print(df1.drop(columns=['영어'],axis=1))
print()
print(df1.drop(index=['서준'],axis=0))
df1

NameError: name 'pd' is not defined

In [108]:
df_copy = df1
df_copy.drop('연아',axis=0,inplace=True)

In [110]:
df1

국어  영어   체육
서준  90  80   70
준서  98  89   95
인아  85  95  100

In [128]:
exam_data = [[ 90, 80, 70],  [ 98, 89, 95],
              [ 85, 95, 100],  [ 100, 90, 90]]

df1 = pd.DataFrame(exam_data,index=['서준','준서','인아','연아'],columns=['국어','영어','수학'])

df1_copy_1 = df1.copy()
df1_copy_1.drop('연아',axis=False,inplace=True)
print(df1_copy_1)
print()
print(df1)

    국어  영어   수학
서준  90  80   70
준서  98  89   95
인아  85  95  100

     국어  영어   수학
서준   90  80   70
준서   98  89   95
인아   85  95  100
연아  100  90   90


In [130]:
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}
df = pd.DataFrame(exam_data, index=['서준','우현','인아'])
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [141]:
# 행을 선택 : object.loc[인덱스명]       인덱스명으로 선택
#             object.iloc[정수인덱스]        숫자 인덱스로 선택
print(df.loc['서준'])
print()
print(df.iloc[0])
print()

# 범위로 선택 : 서준과 우현의 자료 검색
# 인덱스명으로 검색 object.loc[start:end] -> end포함
# 정수인덱스로 검색 object.iloc[start;end] -> end미포함
print(df.loc['서준':'우현'])
print()
print(df.iloc[0:2])
print()

# 서준 인아 출력
print(df.loc[['서준','인아']])
print()
print(df.iloc[[0,2]])

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

    수학  영어   음악   체육
서준  90  98   85  100
인아  70  95  100   90
    수학  영어   음악   체육
서준  90  98   85  100
인아  70  95  100   90


In [143]:
# 열을 선택 : object[컬럼명] 또는 object.컬럼명
print(df.수학)
print()

print(df[['수학','체육']])

서준    90
우현    80
인아    70
Name: 수학, dtype: int64

    수학   체육
서준  90  100
우현  80   90
인아  70   90


In [151]:
# 원소 선택 : object.loc[행인덱스명,컬럼인덱스명]
#             object.iloc[행의 정수덱스,컬럼의 정수인덱스]
# 행을 슬라이싱 : object.iloc[시작인덱스:끝인덱스:간격]
print(df.iloc[0:3:2])
print(df.iloc[::2])
print(df.iloc[::-1])
# 인아의 수학과 체육 점수를 출력
df.loc['인아',['수학','체육']]
df.iloc[-1,[0,-1]]
# 서준부터 우현까지 수학에서 음악 점수를 출력
df.loc['서준':'우현','수학':'음악']

    수학  영어   음악   체육
서준  90  98   85  100
인아  70  95  100   90
    수학  영어   음악   체육
서준  90  98   85  100
인아  70  95  100   90
    수학  영어   음악   체육
인아  70  95  100   90
우현  80  89   95   90
서준  90  98   85  100


수학  영어  음악
서준  90  98  85
우현  80  89  95

In [161]:
# 열 추가 : object['새로운 컬럼명'] = 값
# '국어' 점수 추가 100
df['국어'] = 100
print(df)

# 행 추가 : object.loc[새로운 행 이름] = 값 또는 배열
df.loc['철수'] = [99,80,90,100,80]
df

    수학  영어   음악   체육   국어
서준  90  98   85  100  100
우현  80  89   95   90  100
인아  70  95  100   90  100
철수  99  80   90  100  100


수학  영어   음악   체육   국어
서준  90  98   85  100  100
우현  80  89   95   90  100
인아  70  95  100   90  100
철수  99  80   90  100   80

In [165]:
# 서준의 영어 점수를 100으로 수정
df.loc['서준','영어'] = 100
df.iloc[0,1] = 100
df

수학   영어   음악   체육   국어
서준  90  100   85  100  100
우현  80   89   95   90  100
인아  70   95  100   90  100
철수  99   80   90  100   80

In [169]:
# 서준의 수학 점수와 국어 점수를 77로 수정
df.loc['서준',['수학','국어']] = 77
print(df)
# 우현의 수학 점수와 국어 점수를 77, 88로 수정
df.loc['우현',['수학','국어']] = 77 ,88
print(df)

    수학   영어   음악   체육   국어
서준  77  100   85  100   77
우현  77   89   95   90   88
인아  70   95  100   90  100
철수  99   80   90  100   80
    수학   영어   음악   체육   국어
서준  77  100   85  100   77
우현  77   89   95   90   88
인아  70   95  100   90  100
철수  99   80   90  100   80


In [174]:
# 행과 열의 위치 변경 : objecyt.transpose(), object.T
df_t = df.T
df_t.transpose()

수학   영어   음악   체육   국어
서준  77  100   85  100   77
우현  77   89   95   90   88
인아  70   95  100   90  100
철수  99   80   90  100   80

In [ ]:
#시리즈를 생성 : pandas.Series(딕셔너리 또는 리스트)
# 데이터프레임 생성 : pandas.DataFrame(데이터,index=[],column=[])
# 데이터프레임의 인덱스 변경 : object.index = [인덱스명,...]
# 데이터프레임의 컬럼 변경 : object.columns = [컬럼명,...]
# object.함수명( , , , , , inplace=True) -> 기존자료변경
# 인덱스명과 컬럼명을 일부 변경 : object.rename(index = {old:new, ...},inplace=True/False)
#                                  object.rename(columns = {old:new, ...},inplace=True/False)
# 인덱스와 컬럼삭제 : object.drop(인덱스명,axis = 0)        axis = 0 생략가능
# 인덱스와 컬럼삭제 : object.drop(컬럼명,axis = 1)
# 원소 수정 : object.loc[인덱스명,컬럼명 ] = 값
# 행 추가 : object.loc[새로운 인덱스명] = 값 또는 배열
# 열 추가 : object[새로운 컬럼명] = 값
# 행 자료 검색 : object.loc[행명] , loc[start:end, 컬럼의 start:end]
# 열 자료 검색 : objecr[열명] 
# 인덱스와 컬럼의 위치 변경 : object.transpose(), object.T




In [232]:
exam_data = {'이름':['서준','우현','인아'],
            '수학':[90,80,70],
            '영어':[100,80,90],
            '음악':[100,90,100],
            '체육':[90,80,70]}

df = pd.DataFrame(exam_data)
df

이름  수학   영어   음악  체육
0  서준  90  100  100  90
1  우현  80   80   90  80
2  인아  70   90  100  70

In [233]:
# 특정 컬럼을 인덱스로 설정 : object.set_index(컬럼명)
# 이름 컬럼을 인덱스로 설정
df.set_index('이름',inplace=True)
df

수학   영어   음악  체육
이름                  
서준  90  100  100  90
우현  80   80   90  80
인아  70   90  100  70

In [234]:
#인덱스 초기화 : object.resrt_index()
df.reset_index(inplace=True)
df

이름  수학   영어   음악  체육
0  서준  90  100  100  90
1  우현  80   80   90  80
2  인아  70   90  100  70

In [235]:
ndf = df.set_index('이름')
ndf

수학   영어   음악  체육
이름                  
서준  90  100  100  90
우현  80   80   90  80
인아  70   90  100  70

In [236]:
# 인덱스를 재배열 : object.reindex(인덱스리스트)
idx_list = ['서준','철수','우현','인아','나래']
ndf_1 = ndf.reindex(idx_list)
ndf_1

수학     영어     음악    체육
이름                          
서준  90.0  100.0  100.0  90.0
철수   NaN    NaN    NaN   NaN
우현  80.0   80.0   90.0  80.0
인아  70.0   90.0  100.0  70.0
나래   NaN    NaN    NaN   NaN

In [237]:
# 인덱스 기준으로 정렬 : object.sort_index()
ndf_1.sort_index()
ndf_1


수학     영어     음악    체육
이름                          
서준  90.0  100.0  100.0  90.0
철수   NaN    NaN    NaN   NaN
우현  80.0   80.0   90.0  80.0
인아  70.0   90.0  100.0  70.0
나래   NaN    NaN    NaN   NaN

In [239]:
# 컬럼값을 기준으로 정렬: object.sort_values(by=컬럼,ascending=False)
ndf.sort_values(by=['수학','음악'],ascending=False)

수학   영어   음악  체육
이름                  
서준  90  100  100  90
우현  80   80   90  80
인아  70   90  100  70

In [ ]:
# df.set_index(), df.reset_index(), df.reindex(인덱스리스트)
# df.sort_index(), df.sort_values(by=[컬럼, ..],ascending=False)

# PART1 4.산술연산

In [243]:
# 1. 시리즈 연산
student1 = pd.Series({'국어':100,'영어':80,'수학':90})
print(student1)

# 각 점수를 100으로 나눈 값을 출력
print(student1/100)
print(student1+100)

국어    100
영어     80
수학     90
dtype: int64
국어    1.0
영어    0.8
수학    0.9
dtype: float64
국어    200
영어    180
수학    190
dtype: int64


In [245]:
# 시리즈 vs 시리즈 연산 : 시리즈 연산자(+-/*) 시리즈
student2 = pd.Series({'국어':90,'영어':80,'수학':100})
student1 + student2

국어    190
영어    160
수학    190
dtype: int64

In [246]:
add = student1 + student2
sub = student1 - student2
mul = student1 * student2
div = student1 / student2
df = pd.DataFrame([add,sub,mul,div],
                 index=['+','-','*','/'])
df

국어      영어      수학
+   190.000000   160.0   190.0
-    10.000000     0.0   -10.0
*  9000.000000  6400.0  9000.0
/     1.111111     1.0     0.9

In [249]:
# 연산식에 Nan이 존재하면 연산의 결과는 Nan
import numpy as np

stud1 = pd.Series({'국어':np.nan,'수학':100,'영어':80})
stud2 = pd.Series({'국어':100,'수학':100})


In [255]:
add = stud1 + stud2
sub = stud1 - stud2
mul = stud1 * stud2
div = stud1 / stud2
df = pd.DataFrame([add,sub,mul,div],
                 index=['+','-','*','/'])
df

국어       수학  영어
+ NaN    200.0 NaN
- NaN      0.0 NaN
* NaN  10000.0 NaN
/ NaN      1.0 NaN

In [272]:
# 데이터프레임 연산
# 데이터프레임 연산자(+,-,*,/) 숫자
# seaborn에서 제공하는 데이터셋을 로드
import seaborn as sns

# titanic 데이터 셋을 불러옴 : sns.load_dataset('titanic')
titanic = sns.load_dataset('titanic')
titanic

# titanic에서 age와 fare 컬럼의 정보만 가져와서 df 에 저장
df = titanic[['age','fare']]
df = titanic.loc[:,['age','fare']]

# 100번째 부터 200번째 까지의 age와 fare만
df = titanic.loc[100:200,['age','fare']]

# df.head() : 처음부터 5개만, df.head(10) 10개, df.tail() 뒤에서 5개 df.tail(10) 뒤 10개
df.head(10)
# df.tail()


age     fare
100  28.0   7.8958
101   NaN   7.8958
102  21.0  77.2875
103  33.0   8.6542
104  37.0   7.9250
105  28.0   7.8958
106  21.0   7.6500
107   NaN   7.7750
108  38.0   7.8958
109   NaN  24.1500

In [275]:
add_df = df + 10
add_df.tail()

age     fare
196   NaN  17.7500
197  52.0  18.4042
198   NaN  17.7500
199  34.0  23.0000
200  38.0  19.5000

In [276]:
(df + add_df).head()

age      fare
100  66.0   25.7916
101   NaN   25.7916
102  52.0  164.5750
103  76.0   27.3084
104  84.0   25.8500

In [257]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'exercise',
 'flights',
 'fmri',
 'gammas',
 'geyser',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'taxis',
 'tips',
 'titanic']

In [280]:
sr_age = titanic.loc[:,'age']
type(sr_age)
(sr_age+100).head()

0    122.0
1    138.0
2    126.0
3    135.0
4    135.0
Name: age, dtype: float64

In [281]:
df_mpg = sns.load_dataset('mpg')
df_mpg.info()
# mpg데이터셋을 로드해서 
# 1. mpg, weight 컬럼을 추출해서 데이터프레임으로 생성 한 후
# 2. 각 원소에 100을 더한 값을 출력
# 3. 데이터프레임을 처음 10개의 정보만 출력
# 4. 처음부터 100개의 행만 추출하여 mpg_sample 데이터프레임 생성


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64  
 7   origin        398 non-null    object 
 8   name          398 non-null    object 
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB
